apiVersion: v1
kind: Service
metadata:
  name: dns2
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  loadBalancerIP: 172.17.255.2
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
