apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: dev
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jane-admin-dev
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    namespace: dev
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
