# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network",
    bridge: "Default Switch",
    type: "dhcp"
  config.vm.provider "hyperv" do |h|
    h.mac = "00155D00753A"
    h.cpus = 4
    h.enable_virtualization_extensions = true
    h.maxmemory = nil
    h.memory = 8192
    h.vmname = "ubuntu-minikube"
    h.auto_start_action = "Nothing"
    h.auto_stop_action = "ShutDown"
    h.enable_automatic_checkpoints = false
    h.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: false,
      vss: true
    }
  end
  config.vm.provision "file", source: "~/.ssh/vagrant.pub", destination: "~/.ssh/vagrant.pub"
  config.vm.provision "shell", inline: "cat ~vagrant/.ssh/vagrant.pub >> ~vagrant/.ssh/authorized_keys"
end
