apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: server
          image: quay.io/prometheus/node-exporter
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
