- hosts: all
  gather_facts: yes
  roles:
    - role: gantsign.minikube
    - role: ferrarimarco.virtualbox
      become: yes
  tasks:
    - name: Start minikube
      shell: "minikube start"
    - name: Start dashboard
      shell: "minikube dashboard &"
      async: 10
      poll: 0
    - name: Get kubectl stable version
      uri:
        url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
        return_content: yes
      register: kubectl_version
    - name: Show kubectl version
      debug:
        msg: "{{ kubectl_version.content  | replace('\n', '') }}"
    - name: Download kubectl stable version
      become: true
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content | replace('\n', '') }}/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin"
        mode: "0755"
    - name: Run kubectl proxy
      shell: "kubectl proxy --address 0.0.0.0 --accept-hosts '.*' --port 8080 &"
      async: 10
      poll: 0
      register: kubectl_proxy

#TODO: copy config and certs onto host
# DEFAULT_ROUTE=$(ip route show default | awk '/default/ {print $3}')
# CLIENT_CERT=$(kubectl config view | grep client-certificate | awk '/client-certificate/ {print $2}')
# CLIENT_KEY =$(kubectl config view | grep client-key | awk '/client-key/ {print $2}')
# And too: certificate-authority: /home/vagrant/.minikube/ca.crt
# Copy three files to host system with vagrant scp
# kubectl config set-cluster
# kubectl config set-credentials
# kubectl config set-context
# kubectl config use-context
